### ISSUE TITLE
[1.12.2] Armor Bar floats if you have Absorption with Scaling Health or Mantle.

### ISSUE THREAD

**Issue by SonicX8000** [Tfarcenim/OverloadedArmorBar#1]
Minecraft: 1.12.2
Forge: 14.23.5.2808

Mods: 2
Mantle-1.12-1.3.3.42
overloadedarmorbar-1.0.2

-OR-

Mods: 3
overloadedarmorbar-1.0.2
ScalingHealth-1.12.2-1.3.33+135
SilentLib-1.12.2-3.0.13+167

-----
![](https://cdn.discordapp.com/attachments/377171551155650560/551888459241881602/overpoweredbarfloatx.PNG)
Left is Scaling Health. Right is Mantle. I have 60 Absorption which is 3 rows.

Health's fine but if you have more than one row of Absorption using Scaling Health's/Mantles overlay... the Armor Bar floats. Normally you can't get that much absorption by normal means but with a mod called "Natural Absorption" which allows absorption to recharge overtime if you avoid taking damage for some time as well as upgrading it via Books or Absorption Enchantment... yea.

**Comment by Tfarcenim** [comment]
So the issue appears to be similar to the old one where it would float if health was above 20, easy fix.

**Comment by Tfarcenim** [comment]
Fixed as of latest release https://minecraft.curseforge.com/projects/overloaded-armor-bar/files/2683833
