### ISSUE TITLE
Uh its working but at the same time its not...

### ISSUE THREAD

**Issue by Plasman888** [Tfarcenim/OverloadedArmorBar#13]
![2020-10-21_18 25 53](https://user-images.githubusercontent.com/71266194/96707844-fa624d80-13ca-11eb-80a5-42a580b0400a.png)
Am I doing something wrong?

**Comment by Tfarcenim** [comment]
It is working, but you need to disable rustic's armor overlay in their config.

**Comment by Plasman888** [comment]
Ah I see thanks
