### ISSUE TITLE
1.17/1.18 [Suggestion]

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [Tfarcenim/OverloadedArmorBar#14]
Are there plans for porting to 1.17/1.18? If not, how hard it would be? I really like this mod, and I might attempt porting it myself as long as you think it could work and you're ok with it.

**Comment by Tfarcenim** [comment]
Fabric is done, Forge will be done when it's stable

**Comment by BeansBeefBroccoli** [comment]
Thx so much man!
