### ISSUE TITLE
[BUG] Displays incorrect armor value with the Origins mod

### ISSUE THREAD

**Issue by zombieseatflesh7** [Tfarcenim/OverloadedArmorBar#16]
The Origins mod: https://www.curseforge.com/minecraft/mc-mods/origins
The Origins mod adds functions to modify the players armor value based on certain conditions. This displays the correct armor value in vanilla, but not when using OverloadedArmorBar. This affects the origin "Shulker", and the origin "Piglin" (from the ExtraOrigins mod).

**Comment by Tfarcenim** [comment]
Fixed in 5.1
