### ISSUE TITLE
absorption and health boost rendering over armor bar

### ISSUE THREAD

**Issue by ChloeIsNobody** [Tfarcenim/OverloadedArmorBar#18]
when the player has bonus hearts by any affect, they will render over the armor bar
![Capture](https://user-images.githubusercontent.com/64283247/155942417-e0733193-a545-4287-9ee2-293202fb15c7.PNG)

**Comment by Tfarcenim** [comment]
Fabric?

**Comment by ChloeIsNobody** [comment]
yes, this is fabric 1.18.1

**Comment by Tfarcenim** [comment]
Fixed in 6.1
