### ISSUE TITLE
Hunger and Experience bars hidden in F5 Modes

### ISSUE THREAD

**Issue by joshuafinch** [Tfarcenim/OverloadedArmorBar#2]
The player's hunger and experience bars are getting hidden when the user enters F5 (third person) mode.

OverloadedArmorBar version 1.0.3 for 1.12.2
Forge Mod Loader version 14.23.5.2814 
Minecraft 1.12.2

No other mods are installed.

Without F5 Mode:
![HungerAndExpShown](https://user-images.githubusercontent.com/7941898/54819676-91699f80-4c94-11e9-82b4-91502ddbb4b1.PNG)

With F5 Mode:
![HungerAndExpHidden](https://user-images.githubusercontent.com/7941898/54819675-91699f80-4c94-11e9-8f8c-4edf5ada185e.PNG)

**Comment by Tfarcenim** [comment]
fixed in 1.0.4
