### ISSUE TITLE
[1.18.2] Armor Bar renders over Chat

### ISSUE THREAD

**Issue by Diedntgo** [Tfarcenim/OverloadedArmorBar#23]
For some reason the armor bar covers up the chat, when in Vanilla chat is displayed over the armor bar

Vanilla:
![2023-02-14_16 12 12](https://user-images.githubusercontent.com/64341357/218865770-d5656bcf-98d2-43ee-aa8e-6fe663627ddf.png)

Overloaded Armor Bar:
![2023-02-14_16 07 50](https://user-images.githubusercontent.com/64341357/218865529-68dee14c-fa7c-463d-ae10-f526fa964a85.png)

This is on the latest version for 1.18.2 on Forge

**Comment by Tfarcenim** [comment]
fixed in 6.1
