### ISSUE TITLE
Fabric 1.20.1 crash due to invalid hardcoded mixin refmap reference

### ISSUE THREAD

**Issue by Linguardium** [Tfarcenim/OverloadedArmorBar#28]
https://github.com/Tfarcenim/OverloadedArmorBar/blob/264128819cf9af452c868178849131d26d4df43d/src/main/resources/mixins.overloadedarmorbar.json#L4

https://github.com/Tfarcenim/OverloadedArmorBar/blob/264128819cf9af452c868178849131d26d4df43d/gradle.properties#L12

hardcoded refmap filename doesnt match archive name leading to invalid reference and crashes due to failure to remap intermediary.

issue likely affects 1.18 fabric versions as well

**Comment by Tfarcenim** [comment]
fixed, open a issue for the relevant versions if present.
