### ISSUE TITLE
Transparency turns black in 3rd Person 

### ISSUE THREAD

**Issue by naqaden** [Tfarcenim/OverloadedArmorBar#3]
Tested with only:
Overloaded Armor Bar v1.0.4a
Forge v14.23.5.2808
MC 1.12.2

![overloadedarmorbar](https://user-images.githubusercontent.com/8063786/54960998-482b8100-4f1c-11e9-9cdc-54eb25605c35.PNG)

**Comment by Tfarcenim** [comment]
fixed in 1.04b

**Comment by naqaden** [comment]
Thanks for the quick fix. I'm interested to see how the fix was done since I have a similar problem in an experimental mod of mine.

**Comment by naqaden** [comment]
I worked it out: GlStateManager.enableAlpha(); Thanks again.

**Comment by Tfarcenim** [comment]
I used enable blend but yeah
