### ISSUE TITLE
Any plans to add mods to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [Tfarcenim/OverloadedArmorBar#35]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if your mods were also in Modrinth, otherwise I have to download them separately for each modpack and check for theirs updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool mods could be downloaded from the second most popular Minecraft modding site.

**Comment by Tfarcenim** [comment]
Yes, however rollout will be slow and only for 1.21+ because I don't want to touch gradle any more than I have to.

**Comment by Alter73** [comment]
Okay, I'm glad to hear that. Thanks for the answer!
