### ISSUE TITLE
[1.12.2] Conflict with Random Things. Lava Charm Bar no longer renders.

### ISSUE THREAD

**Issue by SonicX8000** [Tfarcenim/OverloadedArmorBar#4]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 2
overloadedarmorbar-1.0.4b
RandomThings-MC1.12.2-4.2.7

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/564219974793822229/lavacharmbarbug.PNG)

Top:
Lava Charm Bar doesn't show if Overloaded Armor Bar is installed.

Bottom:
Lava Charm Bar shows if Overloaded Armor Bar isn't installed.

**Comment by Tfarcenim** [comment]
oh dear...

**Comment by Tfarcenim** [comment]
1.0.4c should fix this

**Comment by SonicX8000** [comment]
The bar renders now... but...
![](https://cdn.discordapp.com/attachments/377171551155650560/564666763896422402/lavabardiscolor.PNG)
Whatever color you have set for the first row of the Armor Bar will leak into the first icon of the Lava Bar.

**Comment by Tfarcenim** [comment]
fixed in 1.0.4d

**Comment by SonicX8000** [comment]
![](https://cdn.discordapp.com/attachments/377171551155650560/564689874993545226/overloadedhungerbar.PNG)
Now it leaks into the hunger bar. Wasn't sure to make a new issue about it.

This is with only the Overloaded Armor mod, using 1.0.4d.

**Comment by Tfarcenim** [comment]
i want to die, brb

**Comment by Tfarcenim** [comment]
try 1.0.4e, I think I got every edge case

**Comment by SonicX8000** [comment]
Yup, appears to be fixed now. If anything else occurs I'll let you know.
