### ISSUE TITLE
[Suggestion] Add in the Bedrock layer from the Toughness Bar.

### ISSUE THREAD

**Issue by SonicX8000** [Tfarcenim/OverloadedArmorBar#5]
Currently there's no Bedrock layer if one has oh-so-much armor. Could there be a config option for this? Like...

If enabled: Bronze -> silver -> gold -> platinum -> bedrock -> bedrock.

If disabled: Bronze -> silver -> gold -> platinum -> platinum -> platinum

Also ensure that the bedrock layer doesn't use the first colored layer.

**Comment by Tfarcenim** [comment]
I will see about adding a bedrock layer as the final one, it may break texture backs though

**Comment by SonicX8000** [comment]
Break texture backs?

**Comment by Tfarcenim** [comment]
yes, it would break any texture packs that get to the final bar because it will need to use a custom texture as it can't be a simple recolor like the other layers.

**Comment by SonicX8000** [comment]
Ah, I see.

**Comment by SonicX8000** [comment]
Just curious on how this suggestion was doing.

**Comment by Tfarcenim** [comment]
I haven't found a good non - resource pack breaking solution yet, but I am working on the toughness bar thing now.

**Comment by SonicX8000** [comment]
Ah, alright.

**Comment by Tfarcenim** [comment]
Yeah, there's no way to implement it that works with resource packs, and frankly if a mod has that many layers, it's on them because anything above 30 is meaningless in normal play.
