### ISSUE TITLE
[1.12.2] Odd Armor Bar shift.

### ISSUE THREAD

**Issue by SonicX8000** [Tfarcenim/OverloadedArmorBar#6]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 3
overloadedarmorbar-1.0.4e
ScalingHealth-1.12.2-1.3.33+135
SilentLib-1.12.2-3.0.13+167

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/569562276936548363/armorbarshift.PNG)

Top:
If your have less than 20 max health, depending on how much absorption you have... it'll cause absorption & armor bars to overlap until it reaches a certain point.

Middle:
I have enough absorption so the bars render correctly now.

Bottom:
This is how it looks without Overloaded Armor Bar installed.

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/569560467240910869/armorbarshiftNA.PNG)
One more thing to note... if using the Natural Absorption Mod this can happen with the rendering. One of the absorb hearts is clipped into the armor bar but when it recovers it'll shift back to normal.

This may also happen with Mantle as well as maybe just vanilla although that I am unsure.

**Comment by Tfarcenim** [comment]
Issue with floor functions, should be fixed.

**Comment by SonicX8000** [comment]
Can confirm that is this fixed. Sorry for the late response.
