### ISSUE TITLE
[1.12.2] Excessive armor bar shift w/ Colorful Health Bar

### ISSUE THREAD

**Issue by rayblon** [Tfarcenim/OverloadedArmorBar#7]
Not sure whether the issue is the armor hud or colorful health bar, so I'm putting it here. I made a hat with +500 hp on it, and when the health updates above default, it snaps up as though there were actually 26 health bars on the screen.
![armor bug](https://user-images.githubusercontent.com/46195554/57579384-02456080-7469-11e9-8964-77003e5c4238.png)

Version 1.0.4

**Comment by Tfarcenim** [comment]
which 1.04 because with 1.0.4f everything looks fine, there was an issue in the earlier versions of the mod with this so I removed the mod detection and made it a config option instead.

**Comment by rayblon** [comment]
Oh, setting that override option you mentioned to false fixed it. Thanks!
